SELECT *FROM BRONZE.LOC_A101;
SELECT *FROM BRONZE.CRM_CUSTOMER_INFO;
SELECT DISTINCT CNTRY FROM BRONZE.LOC_A101

TRUNCATE TABLE SILVER.LOC_A101
PRINT('TRUNCATING THE TABLE')
INSERT INTO SILVER.LOC_A101(CID,
							CNTRY)
SELECT REPLACE( CID ,'-','')AS CID,
CASE WHEN TRIM(CNTRY) = 'DE' THEN 'Germany'
WHEN TRIM(CNTRY) IN ('US','USA')THEN 'United States'
WHEN TRIM(CNTRY) IS NULL THEN 'NA' ELSE TRIM(CNTRY) END AS CNTRY
FROM BRONZE.LOC_A101;

SELECT *FROM SILVER.LOC_A101;
