-- 1.WA SQL QUERY TO SLICE THE STRING AND REPLACE THE CHARACTERS USING 
-- 2.WA SQL QUERY TO MANAGE THE COST
--ANS2. IF THEIR IS ONLY CASE WHICH IS NULL THEN WE HAVE A FUNCTION ISNULL WHICH TAKES 
-- TWO PARAMETERS
--3. WA AQL QUERY TO MANAGE DATE
--4.INSERT DATA INTO SILVER.PRD_INFO

TRUNCATE TABLE SILVER.PRD_INFO;
PRINT('TRUNCATING THE TABLE');
INSERT INTO SILVER.PRD_INFO(
							PRD_ID,
							PRD_KEY,
							PRD_NM,
							PRD_COST,
							PRD_LINE,
							PRD_START_DT,
							PRD_END_DT)
SELECT PRD_ID,
	   REPLACE(SUBSTRING(PRD_KEY,1,5),'-','_')+
	   SUBSTRING(PRD_KEY,7,LEN(PRD_KEY)) AS PRD_KEY,
	   PRD_NM,
	   ISNULL(PRD_COST,0) AS PRD_COST,
     CASE 
    WHEN UPPER(PRD_LINE) = 'R' THEN 'RACE'
    WHEN UPPER(PRD_LINE) = 'S' THEN 'SPEED'
    WHEN UPPER(PRD_LINE) = 'M' THEN 'MILEAGE'
    ELSE 'NA' END AS PRD_LINE,

	   PRD_START_DT,
	   LEAD(PRD_START_DT)OVER(PARTITION BY PRD_KEY ORDER BY PRD_START_DT)AS 
	   PRD_END_DT 
	   FROM BRONZE.PRD_INFO
