-- CHECKING THE UNWANTED SPACES
TRUNCATE TABLE SILVER.PX_CAT_G1V2
PRINT('TRUNCATING THE TABLE')

INSERT INTO SILVER.PX_CAT_G1V2(ID,
								CAT,
								SUBCAT,
								MAINTENANCE)
SELECT ID,
	   CAT,
	   SUBCAT,
	   MAINTENANCE
FROM BRONZE.PX_CAT_G1V2;



-- CHECKING DATA CONSISTENCY
SELECT DISTINCT MAINTENANCE FROM BRONZE.PX_CAT_G1V2

-- INSERT INTO SILVER
SELECT *FROM SILVER.PX_CAT_G1V2