--SELECT * FROM BRONZE.CRM_CUSTOMER_INFO
--WHERE CST_ID = 26499;
SELECT COUNT(*) FROM BRONZE.CRM_CUSTOMER_INFO;
SELECT COUNT(*) FROM BRONZE.PRD_INFO;
SELECT COUNT(*) FROM BRONZE.CUST_AZ12;
SELECT COUNT(*) FROM BRONZE.LOC_A101;
SELECT COUNT(*) FROM BRONZE.PX_CAT_G1V2;