--CREATE STORED PROCEDURE OF SILVER TABEL
--WA SQL QUERY TO CREATE AND STORED PROCEDURE OF ALL THE SILVER LAYER TABLE

CREATE OR ALTER PROCEDURE SILVER.SILVER_PROCEDURE AS
BEGIN 

-- SILVER.CRM_CUSTOMER_INFO
TRUNCATE TABLE SILVER.CRM_CUSTOMER_INFO;
PRINT('TRUNCATING THE TABLE');

INSERT INTO SILVER.CRM_CUSTOMER_INFO(
    CST_ID,
    CST_KEY,
    CST_FIRSTNAME,
    CST_LASTNAME,
    CST_MARITALSTATUS,
    CST_GENDER,
    CST_CREATEDATE
)
SELECT 
    CASE 
        WHEN CST_ID IS NULL THEN 'NA' 
        ELSE CAST(CST_ID AS VARCHAR(12)) 
    END,

    CST_KEY,

    CASE 
        WHEN CST_FIRSTNAME IS NULL THEN 'NA' 
        ELSE TRIM(CST_FIRSTNAME) 
    END,

    CASE 
        WHEN CST_LASTNAME IS NULL THEN 'NA' 
        ELSE TRIM(CST_LASTNAME)
    END,

    CASE 
        WHEN CST_MARITALSTATUS = 'M' THEN 'MARRIED'
        WHEN CST_MARITALSTATUS = 'S' THEN 'SINGLE'
        ELSE 'NA' 
    END,

    CASE 
        WHEN CST_GENDER = 'M' THEN 'MALE'
        WHEN CST_GENDER = 'F' THEN 'FEMALE'
        ELSE 'NA' 
    END,

    CASE 
        WHEN CST_CREATEDATE IS NULL THEN 'NA' 
        ELSE CAST(CST_CREATEDATE AS VARCHAR(10)) 
    END

FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CST_ID 
               ORDER BY CST_CREATEDATE DESC
           ) AS RN
    FROM BRONZE.CRM_CUSTOMER_INFO
) T
WHERE RN = 1;

-- SILVER.CUST_AZ12
TRUNCATE TABLE SILVER.CUST_AZ12;
PRINT('TRUNCATING THE TABLE');

INSERT INTO SILVER.CUST_AZ12 (
    CID,
    BDATE,
    GEN
)
SELECT 
    CID,
    CASE
        WHEN BDATE > GETDATE() THEN NULL 
        ELSE BDATE
    END AS BDATE,
    CASE
        WHEN UPPER(TRIM(GEN)) IN ('F','FEMALE') THEN 'FEMALE'
        WHEN UPPER(TRIM(GEN)) IN ('M','MALE') THEN 'MALE'
        ELSE 'NA'
    END AS GEN
FROM BRONZE.CUST_AZ12;


--SILVER.LOC_A101
TRUNCATE TABLE SILVER.LOC_A101
PRINT('TRUNCATING THE TABLE')
INSERT INTO SILVER.LOC_A101(CID,
							CNTRY)
SELECT REPLACE( CID ,'-','')AS CID,
CASE WHEN TRIM(CNTRY) = 'DE' THEN 'Germany'
WHEN TRIM(CNTRY) IN ('US','USA')THEN 'United States'
WHEN TRIM(CNTRY) IS NULL THEN 'NA' ELSE TRIM(CNTRY) END AS CNTRY
FROM BRONZE.LOC_A101;

--SILVER.PRD_INFO
TRUNCATE TABLE SILVER.PRD_INFO;
PRINT('TRUNCATING THE TABLE');
INSERT INTO SILVER.PRD_INFO(
							PRD_ID,
							PRD_KEY,
							PRD_NM,
							PRD_COST,
							PRD_LINE,
							PRD_START_DT,
							PRD_END_DT)
SELECT PRD_ID,
	   REPLACE(SUBSTRING(PRD_KEY,1,5),'-','_')+
	   SUBSTRING(PRD_KEY,7,LEN(PRD_KEY)) AS PRD_KEY,
	   PRD_NM,
	   ISNULL(PRD_COST,0) AS PRD_COST,
     CASE 
    WHEN UPPER(PRD_LINE) = 'R' THEN 'RACE'
    WHEN UPPER(PRD_LINE) = 'S' THEN 'SPEED'
    WHEN UPPER(PRD_LINE) = 'M' THEN 'MILEAGE'
    ELSE 'NA' END AS PRD_LINE,

	   PRD_START_DT,
	   LEAD(PRD_START_DT)OVER(PARTITION BY PRD_KEY ORDER BY PRD_START_DT)AS 
	   PRD_END_DT 
	   FROM BRONZE.PRD_INFO


--SILVER.PX_CAT_G1V2
TRUNCATE TABLE SILVER.PX_CAT_G1V2
PRINT('TRUNCATING THE TABLE')

INSERT INTO SILVER.PX_CAT_G1V2(ID,
								CAT,
								SUBCAT,
								MAINTENANCE)
SELECT ID,
	   CAT,
	   SUBCAT,
	   MAINTENANCE
FROM BRONZE.PX_CAT_G1V2;
END
