-- CHECKING THE QUALITY OF SILVER.CRM_CUSTOMER_INFO

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY CST_ID ORDER BY CST_ID) AS rn
    FROM SILVER.CRM_CUSTOMER_INFO
)
DELETE FROM CTE
WHERE rn > 1;
SELECT CST_ID ,COUNT(*) FROM SILVER.CRM_CUSTOMER_INFO
GROUP BY CST_ID HAVING COUNT (*) > 1 
OR CST_ID IS NULL;


WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY CST_KEY ORDER BY CST_KEY) AS rn
    FROM SILVER.CRM_CUSTOMER_INFO
)
DELETE FROM CTE
WHERE rn > 1;
SELECT CST_KEY ,COUNT(*) FROM SILVER.CRM_CUSTOMER_INFO
GROUP BY CST_KEY HAVING COUNT (*) > 1 
OR CST_KEY IS NULL;

