TRUNCATE TABLE BRONZE.CRM_CUSTOMER_INFO;
BULK INSERT BRONZE.CRM_CUSTOMER_INFO 
FROM 'C:\Dataset\Source1\cust_info (2).csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT COUNT(*)FROM BRONZE.CRM_CUSTOMER_INFO;

-- CHECK FOR NULL OR DUPLICATES FROM TABLE

SELECT CST_ID,
COUNT(*) 
FROM BRONZE.CRM_CUSTOMER_INFO
GROUP BY CST_ID
HAVING COUNT(*) > 1;

SELECT PRD_ID ,
COUNT(*)
FROM BRONZE.PRD_INFO
GROUP BY PRD_ID
HAVING COUNT(*) >1;

SELECT CID,
COUNT(*)
FROM BRONZE.CUST_AZ12
GROUP BY CID 
HAVING COUNT(*)>1;

SELECT CID,
COUNT(*)
FROM BRONZE.LOC_A101
GROUP BY CID 
HAVING COUNT(*)>1;

SELECT ID,
COUNT(*)
FROM BRONZE.PX_CAT_G1V2
GROUP BY ID 
HAVING COUNT(*)>1;