
--CONSIDERING ONLY ONE DATA 

--SELECT * ,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
--AS UPDATED_DATE 
--FROM BRONZE.CRM_CUSTOMER_INFO WHERE CST_ID = 29466;

--CLEANING PROCESS

SELECT *FROM 
(SELECT *,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
AS UPDATED_RECORD FROM BRONZE.CRM_CUSTOMER_INFO)T WHERE UPDATED_RECORD = 1 
AND CST_ID = 29466;

SELECT *FROM
(SELECT* ,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
AS UPDATED_RECORD FROM BRONZE.CRM_CUSTOMER_INFO )T WHERE UPDATED_RECORD =1
AND CST_ID =29483;

SELECT *FROM 
(SELECT *,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
AS UPDATED_RECORD FROM BRONZE.CRM_CUSTOMER_INFO)T WHERE UPDATED_RECORD = 1 
AND CST_ID = 29433;

SELECT *FROM
(SELECT* ,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
AS UPDATED_RECORD FROM BRONZE.CRM_CUSTOMER_INFO )T WHERE UPDATED_RECORD =1
AND CST_ID =29473;

SELECT *FROM
(SELECT* ,ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY CST_CREATEDATE DESC) 
AS UPDATED_RECORD FROM BRONZE.CRM_CUSTOMER_INFO )T WHERE UPDATED_RECORD =1
AND CST_ID =29449;



