

TRUNCATE TABLE SILVER.CUST_AZ12;
PRINT('TRUNCATING THE TABLE');

INSERT INTO SILVER.CUST_AZ12 (
    CID,
    BDATE,
    GEN
)
SELECT 
    CID,
    CASE
        WHEN BDATE > GETDATE() THEN NULL 
        ELSE BDATE
    END AS BDATE,
    CASE
        WHEN UPPER(TRIM(GEN)) IN ('F','FEMALE') THEN 'FEMALE'
        WHEN UPPER(TRIM(GEN)) IN ('M','MALE') THEN 'MALE'
        ELSE 'NA'
    END AS GEN
FROM BRONZE.CUST_AZ12;

SELECT * 
FROM SILVER.CUST_AZ12;
