--HANDLING THE NULL VALUE AND INSERTING THE DATA INTO SILVER LEVEL
--Q1 WA SQL QUERY TO HANDEL CUSTOMER MARITAL STATUS & GENDER AS WELL IF THEIR IS M IN MARITAL STATUS APPLIES MARRIED IF THEIR IS S APPLIES SINGLE  OR IS NULL APPLY ACC TO USER DEFINED IF THEIR IS CUSTOMMER GENDER IS M APPLY MALE IF F APPLY FEMALE IF THEIR IS NULL APPLY ACC TO USER DEFINED ?

TRUNCATE TABLE SILVER.CRM_CUSTOMER_INFO;
PRINT('TRUNCATING THE TABLE');

INSERT INTO SILVER.CRM_CUSTOMER_INFO(
    CST_ID,
    CST_KEY,
    CST_FIRSTNAME,
    CST_LASTNAME,
    CST_MARITALSTATUS,
    CST_GENDER,
    CST_CREATEDATE
)
SELECT 
    CASE 
        WHEN CST_ID IS NULL THEN 'NA' 
        ELSE CAST(CST_ID AS VARCHAR(12)) 
    END,

    CST_KEY,

    CASE 
        WHEN CST_FIRSTNAME IS NULL THEN 'NA' 
        ELSE TRIM(CST_FIRSTNAME) 
    END,

    CASE 
        WHEN CST_LASTNAME IS NULL THEN 'NA' 
        ELSE TRIM(CST_LASTNAME)
    END,

    CASE 
        WHEN CST_MARITALSTATUS = 'M' THEN 'MARRIED'
        WHEN CST_MARITALSTATUS = 'S' THEN 'SINGLE'
        ELSE 'NA' 
    END,

    CASE 
        WHEN CST_GENDER = 'M' THEN 'MALE'
        WHEN CST_GENDER = 'F' THEN 'FEMALE'
        ELSE 'NA' 
    END,

    CASE 
        WHEN CST_CREATEDATE IS NULL THEN 'NA' 
        ELSE CAST(CST_CREATEDATE AS VARCHAR(10)) 
    END

FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CST_ID 
               ORDER BY CST_CREATEDATE DESC
           ) AS RN
    FROM BRONZE.CRM_CUSTOMER_INFO
) T
WHERE RN = 1;

SELECT *FROM SILVER.CRM_CUSTOMER_INFO;
