BULK INSERT BRONZE.CRM_CUSTOMER_INFO 
FROM 'C:\Dataset\Source1\cust_info (1).csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT *FROM BRONZE.CRM_CUSTOMER_INFO;

BULK INSERT BRONZE.PRD_INFO 
FROM 'C:\Dataset\Source1\prd_info (1).csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT *FROM BRONZE.PRD_INFO;

BULK INSERT BRONZE.CUST_AZ12 
FROM 'C:\Dataset\Source2\CUST_AZ12 (1).csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT *FROM BRONZE.CUST_AZ12;

BULK INSERT BRONZE.LOC_A101
FROM 'C:\Dataset\Source2\LOC_A101.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT *FROM BRONZE.LOC_A101;


BULK INSERT BRONZE.PX_CAT_G1V2
FROM 'C:\Dataset\Source2\PX_CAT_G1V2.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', TABLOCK ); 
SELECT *FROM BRONZE.PX_CAT_G1V2;
