-- WA SQL QUERY TO HANDEL THE VALUES ?
-- MERGE THE TABLE (PRD_INFO,PX_CAT_G1V2)

CREATE VIEW GOLD.DI_START AS 
SELECT
ROW_NUMBER()OVER(ORDER BY PRD_ID)AS PRODUCTION,
      Pn.PRD_ID,
      Pn.PRD_KEY,
      Pn.PRD_NM,
      Pn.PRD_COST,
      Pn.PRD_LINE,
      Pn.PRD_START_DT,
      Pa.ID,
      Pa.CAT,
      Pa.SUBCAT,
      Pa.MAINTENANCE
FROM SILVER.PRD_INFO Pn
CROSS JOIN SILVER.PX_CAT_G1V2 Pa

