-- WA SQL QUERY TO CREATE THE VIEW OF TABLE AND PROVIDE THE UNIQUE KEY TO 
--EACH RECORD(STAR SCHEMA)?USING WINDOW FUNCTION

CREATE VIEW GOLD.SILVER_STARSCHEMA AS
SELECT 
ROW_NUMBER()OVER(ORDER BY CST_ID )AS CUSTOMER_KEY,
    Ci.CST_ID,
    Ci.CST_KEY,
    Ci.CST_FIRSTNAME,
    Ci.CST_LASTNAME,
    Ci.CST_MARITALSTATUS,
    COALESCE(Ci.CST_GENDER, Ca.GEN) AS FINAL_GENDER,
    Ci.CST_CREATEDATE,
    La.CNTRY
FROM SILVER.CRM_CUSTOMER_INFO Ci
LEFT JOIN SILVER.CUST_AZ12 Ca
    ON Ci.CST_KEY = Ca.CID
LEFT JOIN SILVER.LOC_A101 La
    ON Ci.CST_KEY = La.CID;