--COALESCE METHOD TAKES TWO PARAMETERS FIRST IS COLUMM OF MASTER TABLE AND
-- THE VALUE WHICH WE WANT TO SET INTO ANOTHER COLUMM.

-- MERGE THE TABLE (CUST_INFO,CUST_AZ12,LOC_A101)
SELECT 
    Ci.CST_ID,
    Ci.CST_KEY,
    Ci.CST_FIRSTNAME,
    Ci.CST_LASTNAME,
    Ci.CST_MARITALSTATUS,
    COALESCE(Ci.CST_GENDER, Ca.GEN) AS FINAL_GENDER,
    Ci.CST_CREATEDATE,
    La.CNTRY
FROM SILVER.CRM_CUSTOMER_INFO Ci
LEFT JOIN SILVER.CUST_AZ12 Ca
    ON Ci.CST_KEY = Ca.CID
LEFT JOIN SILVER.LOC_A101 La
    ON Ci.CST_KEY = La.CID;